### ISSUE TITLE
CI fails because of missing GLIBC

### ISSUE THREAD

**Issue by Dobiasd** [Dobiasd/FunctionalPlus#276]
```
Run actions/checkout@main
  with:
    repository: Dobiasd/FunctionalPlus
    token: ***
    ssh-strict: true
    persist-credentials: true
    clean: true
    sparse-checkout-cone-mode: true
    fetch-depth: 1
    fetch-tags: false
    show-progress: true
    lfs: false
    submodules: false
    set-safe-directory: true
/usr/bin/docker exec  2249440bb33d7e4486191a91cf26076f26f69a6ccaeac60141dc052702f85b0f sh -c "cat /etc/*release | grep ^ID"
/__e/node20/bin/node: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /__e/node20/bin/node)
```

https://github.com/Dobiasd/FunctionalPlus/actions/runs/6170202179/job/16748394248
